<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- See: https://learn.microsoft.com/en-us/dotnet/standard/frameworks -->
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
    <PackageId>Looplex.OpenForExtension.Loader</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseUrl>https://github.com/looplex-osi/open-for-extension-dotnet/blob/master/LICENSE.md</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/looplex-osi/open-for-extension-dotnet</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Authors>Guilherme Câmara</Authors>
    <Company>Looplex</Company>
    <PackageTags>Looplex;OpenForExtension;Plugin;PluginLoader;</PackageTags>
    <Description>
      Contains a helper for loading classes that implements IPlugin from assemblies.
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Looplex.OpenForExtension\Looplex.OpenForExtension.csproj" />
  </ItemGroup>

</Project>
