<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
	
  <ItemGroup>
	<ProjectReference Include="..\..\src\Looplex.OpenForExtension\Looplex.OpenForExtension.csproj" />
	<ProjectReference Include="..\TheTortoiseAndTheHareAppSample.Domain\TheTortoiseAndTheHareAppSample.Domain.csproj">
	  <ExcludeAssets>runtime</ExcludeAssets>
	</ProjectReference>
  </ItemGroup>
	
</Project>
